# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # step 1: obtain repo from GitHub
      - checkout
      # step 2: create vertual environment and install dependencies
      - run:
          name: install dependencies
          command: |
            conda create --name learning-ci --file requirements.txt
            conda activate learning-ci
      # step 3: run linter and test
      - run:
          name: run test
          command: |
            conda activate learning-ci
            flake8 --statistic
            pytest -v --conv=calculator